# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:48
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(blank=True, max_length=256, verbose_name='avatar_url')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='country')),
                ('gender', models.PositiveSmallIntegerField(choices=[(account.models.Gender(0), 'Female'), (account.models.Gender(1), 'Male'), (account.models.Gender(2), 'Unknown')], default=account.models.Gender(2), verbose_name='gender')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('language', models.CharField(blank=True, help_text='language code', max_length=4, verbose_name='language')),
                ('nickname', models.CharField(blank=True, max_length=128, verbose_name='nickname')),
                ('province', models.CharField(blank=True, max_length=64, verbose_name='province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
