# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:00
from __future__ import unicode_literals

import authx.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(blank=True, max_length=256, verbose_name='avatar_url')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='country')),
                ('gender', models.PositiveSmallIntegerField(choices=[(authx.models.Gender(0), 'Female'), (authx.models.Gender(1), 'Male'), (authx.models.Gender(2), 'Unknown')], default=authx.models.Gender(2), verbose_name='gender')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('language', models.CharField(blank=True, help_text='language code', max_length=4, verbose_name='language')),
                ('nickname', models.CharField(blank=True, max_length=128, verbose_name='nickname')),
                ('province', models.CharField(blank=True, max_length=64, verbose_name='province')),
                ('unionid', models.CharField(blank=True, max_length=128, verbose_name='unionid')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, choices=[(authx.models.UserSource('wx'), 'WX'), (authx.models.UserSource('ali'), 'ALI'), (authx.models.UserSource('phone'), 'Phone')], max_length=8, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Usually wechat openid/ ali user_id', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
