# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:00
from __future__ import unicode_literals

import authx.models
import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, choices=[(authx.models.UserSource('wx'), 'WX'), (authx.models.UserSource('ali'), 'ALI'), (authx.models.UserSource('tinaam'), 'TINAAM')], max_length=8, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='user',
            name='unionid',
            field=models.CharField(blank=True, max_length=128, verbose_name='unionid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Usually wechat openid/ ali user_id', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='username'),
        ),
    ]
