# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=128, verbose_name='serial number')),
                ('state', models.CharField(choices=[('idle', 'IDLE'), ('in_use', 'IN_USE'), ('damaged', 'DAMAGED'), ('repairing', 'REPAIRING'), ('obsolete', 'OBSOLETE'), ('expired', 'EXPIRED')], max_length=8, verbose_name='state')),
                ('cost', models.FloatField(default=0.0, verbose_name='cost')),
                ('purchased_at', models.DateTimeField(null=True, verbose_name='date purchased')),
                ('expiring_at', models.DateTimeField(null=True, verbose_name='expiring date')),
                ('maintainer', models.CharField(blank=True, max_length=64, verbose_name='maintainer')),
                ('maintainer_phone', models.CharField(blank=True, max_length=32, verbose_name='maintainer phone')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Partner')),
                ('stockrecord', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='partner.StockRecord', verbose_name='StockRecord', null=True)),
            ],
            options={
                'verbose_name': 'Partner Asset',
                'verbose_name_plural': 'Partner Assets',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='partnerasset',
            unique_together=set([('partner', 'serial_num')]),
        ),
    ]
