# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20171030_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='code')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.PartnerAsset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset Location',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='assetlocation',
            unique_together=set([('code',)]),
        ),
    ]
